name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: CI
    permissions:
      pull-requests: read
      contents: read
      actions: write
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v2
    with:
      endtoend: false
      phpcoverage_force_off: true
      js: false
      composer_require_extra: silverstripe/cms:^4 || ^5
